on: push

name: CI/CD
jobs:
  web-deploy:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v4

    - name: Install rust
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

    - uses: Swatinem/rust-cache@v2.7.7

    - name: Test
      run: cargo test

    - name: Lint
      run: cargo clippy
