on: push

name: CI/CD
jobs:
  - Build without relative-to-macro:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v4

    - name: Install rust
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy

    - uses: Swatinem/rust-cache@v2.7.7

    - name: Test
      run: cargo test

    - name: Lint
      run: cargo clippy

  - Build with relative-to-macro:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install rust
      run: rustup update nightly && rustup default nightly && rustup component add clippy

    - uses: Swatinem/rust-cache@v2.7.7

    - name: Test
      run: cargo test --features relative-to-macro

    - name: Lint
      run: cargo clippy --features relative-to-macro
